SIPI_CRM_System/Pages/AdminPanelPage/AdminPanelPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SIPI_CRM_System.Models;
using SIPI_CRM_System.Services.AdminPanelRep;

namespace SIPI_CRM_System.Pages.AdminPanelPage;

public class AdminPanelPage : PageModel
{
    private static string redirectUserString = "";
    private readonly IAdminPanelRepository _repository;
    
    public IEnumerable<Table> Tables { get; set; }
    public IEnumerable<Position> Positions { get; set; }
    public IEnumerable<Employee> Employees { get; set; }

    public AdminPanelPage(IAdminPanelRepository repository)
    {
        _repository = repository;
    }
    
    public IActionResult OnPostAddTable()
    {
        Tables = _repository.GetTables();
        
        try
        {
            Table table = new Table
            {
                Id = Tables.Any() ? Tables.OrderBy(x => x.Id).Last().Id + 1 : 1,
                Places = int.Parse(Request.Form["Places"]),
            };

            _repository.AddTable(table);

            return Redirect("/AdminPanelPage/AdminPanelPage" + redirectUserString);
        }
        catch (Exception e)
        {
            return Redirect("/AdminPanelPage/AdminPanelPage" + redirectUserString + "&incorrectFormat=True");
        }
    }
    
    public IActionResult OnPostAddPosition()
    {
        Positions = _repository.GetPositions();
        
        try
        {
            Position position = new Position
            {
                Id = Positions.Any() ? Positions.OrderBy(x => x.Id).Last().Id + 1 : 1,
                Name = Request.Form["Name"]
            };

            _repository.AddPosition(position);

            return Redirect("/AdminPanelPage/AdminPanelPage" + redirectUserString);
        }
        catch (Exception e)
        {
            return Redirect("/AdminPanelPage/AdminPanelPage" + redirectUserString + "&incorrectFormat=True");
        }
    }

    public IActionResult OnPostAddEmployee()
    {
        Employees = _repository.GetEmployees();
        Positions = _repository.GetPositions();
        
        try
        {
            Position position = new Position
            {
                Id = Positions.Any() ? Positions.OrderBy(x => x.Id).Last().Id + 1 : 1,
                Name = Request.Form["Position"]
            };

            _repository.AddPosition(position);
            
            Employee employee = new Employee
            {
                Id = Employees.Any() ? Employees.OrderBy(x => x.Id).Last().Id + 1 : 1,
                Name = Request.Form["Name"],
                Login = Request.Form["Login"],
                Password = Request.Form["Password"],
                IsAdmin = Request.Form["IsAdmin"] == "on",
                PositionId = position.Id
            };

            _repository.AddEmployee(employee);

            return Redirect("/AdminPanelPage/AdminPanelPage" + redirectUserString);
        }
        catch (Exception e)
        {
            return Redirect("/AdminPanelPage/AdminPanelPage" + redirectUserString + "&incorrectFormat=True");
        }
    }

    public IActionResult OnPostDeleteEmployee()
    {
        try
        {
            string login = Request.Form["Login"];

            _repository.DeleteEmployeeByLogin(login);

            return Redirect("/AdminPanelPage/AdminPanelPage" + redirectUserString);
        }
        catch (Exception e)
        {
            return Redirect("/AdminPanelPage/AdminPanelPage" + redirectUserString + "&incorrectFormat=True");
        }
    }
    
    public IActionResult OnPostUpdateRights()
    {
        try
        {
            string login = Request.Form["Login"];

            _repository.UpdateEmployeeRightsByLogin(login);

            return Redirect("/AdminPanelPage/AdminPanelPage" + redirectUserString);
        }
        catch (Exception e)
        {
            return Redirect("/AdminPanelPage/AdminPanelPage" + redirectUserString + "&incorrectFormat=True");
        }
    }
    
    
    public void OnGet()
    {
        redirectUserString = "?id=" + Request.Query["id"] + "&isadmin=" + Request.Query["isadmin"];
    }
}

SIPI_CRM_System/Pages/AdminPanelPage/AdminPanelPage.cshtml
@page
@model SIPI_CRM_System.Pages.AdminPanelPage.AdminPanelPage

@{
    string id = Request.Query["id"];
    string isAdmin = Request.Query["isadmin"];

    ViewData["Title"] = "Admin Panel";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<!--Menu Button Offcanvas left-->
<div class="offcanvas offcanvas-start menu-offcanvas"
     tabindex="-1"
     id="offcanvasMenu"
     aria-labelledby="offcanvasMenu">
    <!--Offcanvas header-->
    <div class="offcanvas-header text-light">
        <h5 class="offcanvas-title" id="offcanvasMenu">Главное меню</h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <!--Offcanvas body-->
    <div class="offcanvas-body">
        <nav class="dashboard-nav-list">
            <!--User Page-->
            <a class="navbar-brand" asp-area=""
               asp-page="/UserPage/UserPage"
               asp-route-id="@id"
               asp-route-isadmin="@isAdmin">
                Личный кабинет
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="nav-item-divider"></div>
            <!--Main Page-->
            <a class="navbar-brand" asp-area=""
               asp-page="/MainPage/MainPage"
               asp-route-id="@id"
               asp-route-isadmin="@isAdmin">
                Dashboard
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="nav-item-divider"></div>
            <!--Stock Page-->
            <a class="navbar-brand" asp-area=""
               asp-page="/StockPage/StockPage"
               asp-route-id="@id"
               asp-route-isadmin="@isAdmin">
                Склад
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="nav-item-divider"></div>
            <!--Menu Page-->
            <a class="navbar-brand" asp-area=""
               asp-page="/MenuPage/MenuPage"
               asp-route-id="@id"
               asp-route-isadmin="@isAdmin">
                Меню
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <!--Admin Page-->
            @if (isAdmin == "True")
            {
                <div class="nav-item-divider"></div>
                <a class="navbar-brand" asp-area=""
                   asp-page="/AdminPanelPage/AdminPanelPage"
                   asp-route-id="@id"
                   asp-route-isadmin="@isAdmin">
                    Панель администатора
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            }
        </nav>
    </div>
</div>

<div class="d-grid">
    <button class="btn btn-action text-light m-2 btn-lg"
            data-bs-toggle="offcanvas"
            data-bs-target="#offCanvasRightAddTable"
            aria-controls="offCanvasRightAddTable">
        Добавить стол
    </button>
    <div class="offcanvas offcanvas-end add-offcanvas panel-offcanvas" tabindex="-1"
         id="offCanvasRightAddTable"
         aria-labelledby="offCanvasRightAddTable">
        <div class="offcanvas-header">
            <h1>Добавить стол:</h1>
            <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
            <form asp-page-handler="AddTable"
                  method="post"
                  asp-route-id="@id"
                  asp-route-isadmin="@isAdmin">
                <div class="form-group">
                    <label for="Places">Количество мест:</label>
                    <input type="text" class="form-control" name="Places" placeholder="Количество мест">
                </div>
                <div class="btn-toolbar m-4" role="toolbar">
                    <div class="btn-group me-2" role="group">
                        <button class="btn btn-success">Добавить</button>
                    </div>
                    <div class="btn-group me-2" role="group">
                        <button type="button" class="btn btn-danger" data-bs-dismiss="offcanvas" aria-label="Close">Отменить</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <button class="btn btn-action text-light m-2 btn-lg"
            data-bs-toggle="offcanvas"
            data-bs-target="#offCanvasRightAddPosition"
            aria-controls="offCanvasRightAddPosition">
        Добавить должность
    </button>

    <div class="offcanvas offcanvas-end add-offcanvas" tabindex="-1"
         id="offCanvasRightAddPosition"
         aria-labelledby="offCanvasRightAddPosition">
        <div class="offcanvas-header">
            <h1>Добавить должность:</h1>
            <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
            <form asp-page-handler="AddPosition"
                  method="post"
                  asp-route-id="@id"
                  asp-route-isadmin="@isAdmin">
                <div class="form-group">
                    <label for="Name">Название:</label>
                    <input type="text" class="form-control" name="Name" placeholder="Позиция">
                </div>
                <div class="btn-toolbar m-4" role="toolbar">
                    <div class="btn-group me-2" role="group">
                        <button class="btn btn-success">Добавить</button>
                    </div>
                    <div class="btn-group me-2" role="group">
                        <button type="button" class="btn btn-danger" data-bs-dismiss="offcanvas" aria-label="Close">Отменить</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <button class="btn btn-action text-light m-2 btn-lg"
            data-bs-toggle="offcanvas"
            data-bs-target="#offCanvasRightAddEmployee"
            aria-controls="offCanvasRightAddEmployee">
        Добавить пользователя
    </button>

    <div class="offcanvas offcanvas-end add-offcanvas" tabindex="-1"
         id="offCanvasRightAddEmployee"
         aria-labelledby="offCanvasRightAddEmployee">
        <div class="offcanvas-header">
            <h1>Добавить пользователя:</h1>
            <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
            <form asp-page-handler="AddEmployee"
                  method="post"
                  asp-route-id="@id"
                  asp-route-isadmin="@isAdmin">
                <div class="form-group">
                    <label for="Name">Имя:</label>
                    <input type="text" class="form-control" name="Name" placeholder="Имя">
                </div>
                <div class="form-group">
                    <label for="Login">Логин:</label>
                    <input type="text" class="form-control" name="Login" placeholder="Логин">
                </div>
                <div class="form-group">
                    <label for="Password">Пароль:</label>
                    <input type="text" class="form-control" name="Password" placeholder="Пароль">
                </div>
                <div class="form-check">
                    <label for="IsAdmin">Администратор:</label>
                    <input type="checkbox" class="form-check-input" name="IsAdmin" placeholder="Администратор">
                </div>
                <div class="form-group">
                    <label for="Position">Позиция:</label>
                    <input type="text" class="form-control" name="Position" placeholder="Позиция">
                </div>
                <div class="btn-toolbar m-4" role="toolbar">
                    <div class="btn-group me-2" role="group">
                        <button class="btn btn-success">Добавить</button>
                    </div>
                    <div class="btn-group me-2" role="group">
                        <button type="button" class="btn btn-danger" data-bs-dismiss="offcanvas" aria-label="Close">Отменить</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <button class="btn btn-action text-light m-2 btn-lg"
            data-bs-toggle="offcanvas"
            data-bs-target="#offCanvasRightUpdateRights"
            aria-controls="offCanvasRightUpdateRights">
        Выдать права
    </button>

    <div class="offcanvas offcanvas-end add-offcanvas" tabindex="-1"
         id="offCanvasRightUpdateRights"
         aria-labelledby="offCanvasRightUpdateRights">
        <div class="offcanvas-header">
            <h1>Выдать права администратора:</h1>
            <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
            <form asp-page-handler="UpdateRights"
                  method="post"
                  asp-route-id="@id"
                  asp-route-isadmin="@isAdmin">
                <div class="form-group">
                    <label for="Login">Логин:</label>
                    <input type="text" class="form-control" name="Login" placeholder="Логин">
                </div>
                <div class="btn-toolbar m-4" role="toolbar">
                    <div class="btn-group me-2" role="group">
                        <button class="btn btn-success">Выдать</button>
                    </div>
                    <div class="btn-group me-2" role="group">
                        <button type="button" class="btn btn-danger" data-bs-dismiss="offcanvas" aria-label="Close">Отменить</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <button class="btn btn-action text-light m-2 btn-lg"
            data-bs-toggle="offcanvas"
            data-bs-target="#offCanvasRightDeleteEmployee"
            aria-controls="offCanvasRightDeleteEmployee">
        Удалить пользователя
    </button>
    <div class="offcanvas offcanvas-end add-offcanvas" tabindex="-1"
         id="offCanvasRightDeleteEmployee"
         aria-labelledby="offCanvasDeleteEmployee">
        <div class="offcanvas-header">
            <h1>Удалить пользователя:</h1>
            <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
            <form asp-page-handler="DeleteEmployee"
                  method="post"
                  asp-route-id="@id"
                  asp-route-isadmin="@isAdmin">
                <div class="form-group">
                    <label for="Login">Логин:</label>
                    <input type="text" class="form-control" name="Login" placeholder="Логин">
                </div>
                <div class="btn-toolbar m-4" role="toolbar">
                    <div class="btn-group me-2" role="group">
                        <button class="btn btn-success">Удалить</button>
                    </div>
                    <div class="btn-group me-2" role="group">
                        <button type="button" class="btn btn-danger" data-bs-dismiss="offcanvas" aria-label="Close">Отменить</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    @if (Request.Query["incorrectFormat"] == "True")
    {
        <div class="alert alert-danger mb-4" role="alert">
            Неправильный формат данных
        </div>
    }
</div>