SIPI_CRM_System/Pages/EditPages/DishEditPage/DishEditPage.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SIPI_CRM_System.Models;
using SIPI_CRM_System.Services.DishEditPageRep;

namespace SIPI_CRM_System.Pages.EditPages.DishEditPage
{
	public class DishEditPageModel : PageModel
    {
        private static string redirectUserString = ""; //Необоходимо задавать на каждой станице в методе  OnGet(), по нему происходит сохранение действующего пользователя

        private readonly IDishEditPageRepository _context;

        public Dish dish;

        public List<String> productsCategories;

        public IEnumerable<Product> products;

        public IEnumerable<ProductDish> productDishes;

        public DishEditPageModel(IDishEditPageRepository context)
        {
            _context = context;
        }

        public IActionResult OnPostAddProductDish(int productId, int dishId)
        {
            productDishes = _context.GetProductDishes();
            if (productDishes
                .Where(x => x.DishId == dishId)
                .Where(x => x.ProductId == productId)
                .FirstOrDefault() == default)
            {
                var productDish = new ProductDish
                {
                    Id = _context.GetProductDishes().Any() ? _context.GetProductDishes().Last().Id + 1 : 1,
                    ProductId = productId,
                    DishId = dishId,
                    Amount = 0
                };

                _context.AddProductDish(productDish);
            }

            return Redirect("/EditPages/DishEditPage/DishEditPage" + redirectUserString + "&dishId=" + dishId.ToString());
        }

        public IActionResult OnPostUpdate(int dishId)
        {
            var dishName = Request.Form["DishName"];
            var dishMass = decimal.Parse(Request.Form["DishMass"]);
            var dishCategory = Request.Form["Category"];
            var dishSubCategory = Request.Form["SubCategory"];
            var dishPrice = decimal.Parse(Request.Form["Price"]);

            var updDish = _context.GetDish(dishId);

            if (dishName != updDish.Name || dishMass != updDish.Mass ||
                dishCategory != updDish.Category || dishSubCategory != updDish.SubCategory ||
                dishPrice != updDish.Price)
            {
                updDish.Name = dishName;
                updDish.Mass = dishMass;
                updDish.Category = dishCategory;
                updDish.SubCategory = dishSubCategory;
                updDish.Price = dishPrice;

                _context.UpdateDish(updDish);
            }

            foreach (var updProductDish in updDish.ProductDishes)
            {
                var amount = decimal.Parse(Request.Form["productDishesAmount" + updProductDish.Id.ToString()]);

                _context.UpdateProductDishes(updProductDish.Id, amount);
            }

            return Redirect("/EditPages/DishEditPage/DishEditPage" + redirectUserString + "&dishId=" + dishId.ToString());
        }

        public IActionResult OnPostExit()
        {
            return Redirect("/MenuPage/MenuPage" + redirectUserString);
        }

        public IActionResult OnPostDeleteProductDish(int dishId, int productDishId)
        {
            _context.DeleteProductDish(productDishId);
            return Redirect("/EditPages/DishEditPage/DishEditPage" + redirectUserString + "&dishId=" + dishId.ToString());
        }

        public void OnGet()
        {
            dish = _context.GetDish(int.Parse(Request.Query["dishId"]));

            productsCategories = _context.GetProductsCategoriesList();
            products = _context.GetProducts().OrderBy(x => x.Name);
            productDishes = _context.GetProductDishes();

            redirectUserString = "?id=" + Request.Query["id"] + "&isadmin=" + Request.Query["isadmin"]; //Выражение для сохраниения пользователя, одинаково на каждой станице
        }
    }
}

SIPI_CRM_System/Pages/EditPages/OrderEditPage/OrderEditPage.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SIPI_CRM_System.Models;
using SIPI_CRM_System.Services.MenuPageRep;
using SIPI_CRM_System.Services.OrderEditPageRep;

namespace SIPI_CRM_System.Pages.EditPages.OrderEditPage
{
	public class OrderEditPageModel : PageModel
    {
        private readonly IOrderEditPageRepository _context;
        private static string redirectUserString = ""; //Необоходимо задавать на каждой станице в методе  OnGet(), по нему происходит сохранение действующего пользователя

        public DailyOrder dailyOrder;

        public IEnumerable<DailyOrderDish> dailyOrderDishes;
        public IEnumerable<Dish> dishes;

        public List<string> dishCategories = new();
        public Dictionary<string, List<string>> dishSubCategories = new();

        public OrderEditPageModel(IOrderEditPageRepository context)
        {
            _context = context;
        }

        public IActionResult OnPostExit()
        {
            return Redirect("/MainPage/MainPage" + redirectUserString);
        }

        public IActionResult OnPostAddDishToOrder(int dishId, int orderId)
        {
            dailyOrderDishes = _context.GetDailyOrderDishes();

            if (dailyOrderDishes
                .Where(x => x.DishId == dishId)
                .Where(x => x.DailyOrderId == orderId)
                .FirstOrDefault() == default)
            {
                var dailyOrderDish = new DailyOrderDish()
                {
                    Id = _context.GetDailyOrderDishes().Any() ? _context.GetDailyOrderDishes().Last().Id + 1 : 1,
                    DishId = dishId,
                    DailyOrderId = orderId,
                    Amount = 0
                };

                _context.AddDailyOrderDish(dailyOrderDish);
            }

            return Redirect("/EditPages/OrderEditPage/OrderEditPage" + redirectUserString + "&orderId=" + orderId.ToString());
        }

        public IActionResult OnPostDeleteOrderDish(int dailyOrderDishId, int orderId)
        {
            _context.DeleteDailyOrderDish(dailyOrderDishId);
            return Redirect("/EditPages/OrderEditPage/OrderEditPage" + redirectUserString + "&orderId=" + orderId.ToString());
        }

        public IActionResult OnPostUpdate(int orderId)
        {
            dailyOrder = _context.GetDailyOrder(orderId);

            foreach(var orderDish in dailyOrder.DailyOrderDishes)
            {
                int maxAmount = int.MaxValue;
                foreach (var dishProduct in orderDish.Dish.ProductDishes)
                {
                    if (Decimal.ToInt32(dishProduct.Product.Amount / dishProduct.Amount) < maxAmount)
                    {
                        maxAmount = Decimal.ToInt32(dishProduct.Product.Amount / dishProduct.Amount);
                    }
                }

                int inputAmount = int.Parse(Request.Form["dishAmount" + orderDish.Id.ToString()]);

                if (inputAmount <= maxAmount)
                {
                    _context.UpdateOrderDish(orderDish.Id, inputAmount);
                }
            }

            _context.UpdatePrice(orderId);

            return Redirect("/EditPages/OrderEditPage/OrderEditPage" + redirectUserString + "&orderId=" + orderId.ToString());
        }

        public void OnGet()
        {
            dishCategories = _context.GetDishCategoryList();

            foreach (var item in dishCategories)
            {
                var subCategories = _context.GetDishSubCategoryList(item);

                dishSubCategories.Add(item, subCategories);
            }

            dishes = _context.GetDishes();

            dailyOrderDishes = _context.GetDailyOrderDishes();

            dailyOrder = _context.GetDailyOrder(int.Parse(Request.Query["orderId"]));

            redirectUserString = "?id=" + Request.Query["id"] + "&isadmin=" + Request.Query["isadmin"]; //Выражение для сохраниения пользователя, одинаково на каждой станице
        }
    }
}

SIPI_CRM_System/Pages/EditPages/OrderEditPage/OrderEditPage.cshtml
@page
@model SIPI_CRM_System.Pages.EditPages.OrderEditPage.OrderEditPageModel
@{
    ViewData["Title"] = "Order Edit Page";
    Layout = "~/Pages/Shared/_LoginLayout.cshtml";

    var orderId = Request.Query["orderId"];
}

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h3 class="text-center text-dark">Номер стола - @Model.dailyOrder.Table.Id</h3>
            <h3 class="text-center text-dark">Время - @Model.dailyOrder.OrderDateTime.ToShortDateString() @Model.dailyOrder.OrderDateTime.ToShortTimeString()</h3>
            <!--Update/Delete Form-->
            <form asp-page-handler="Update" asp-route-orderId="@orderId">
            @{
                

                <!--Dish Products-->
                <div class="scroll-card">
                    @foreach (var dailyOrderDishes in Model.dailyOrder.DailyOrderDishes)
                    {
                        int maxAmount = int.MaxValue;
                        var dishAmount = "dishAmount" + dailyOrderDishes.Id.ToString();
                        <div class="card dish-card mb-1">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-5">
                                        <p>@dailyOrderDishes.Dish.Name</p>
                                    </div>
                                    <div class="col-4">
                                        <!--Product Amount in Dish-->
                                        <input type="text" class="form-control" value="@dailyOrderDishes.Amount" name="@dishAmount" />
                                    </div>
                                    <div class="col-2">
                                        <p>шт</p>
                                    </div>
                                    <div class="col-1">
                                        <button class="btn-close btn-sm float-right" asp-page-handler="DeleteOrderDish" asp-route-dailyOrderDishId="@dailyOrderDishes.Id" asp-route-orderId="@orderId"></button>
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer">
                                @foreach (var dishProduct in dailyOrderDishes.Dish.ProductDishes)
                                {
                                    if (Decimal.ToInt32(dishProduct.Product.Amount / dishProduct.Amount) < maxAmount)
                                    {
                                        maxAmount = Decimal.ToInt32(dishProduct.Product.Amount / dishProduct.Amount);
                                    }
                                }
                                <div class="alert alert-warning" role="alert">
                                    Досупно для приготовления - @maxAmount
                                </div>
                            </div>
                        </div>
                    }
                </div>
                <div class="row mt-4 text-center">
                    <div class="col-md-6 d-grid">
                        <!--Udpate Button-->
                        <button class="btn btn-success" asp-page-handler="Update" asp-route-orderId="@orderId">Обновить заказ</button>
                    </div>
                    <div class="col-md-6 d-grid">
                        <!--Exit Button-->
                        <button class="btn btn-danger" asp-page-handler="Exit">Выйти</button>
                    </div>
                </div>
            }
            </form>
        </div>
        <div class="col-md-8">
            <h3 class="text-center text-dark mt-5">Меню</h3>
            <div class="row m-2">
                <div class="col-10">
                    <!--Category Collapse List-->
                    @foreach (var category in Model.dishCategories)
                    {
                        var collapseId = "collapse" + category.Replace(" ", "");
                        <!--Category Collapse-->
                        <div class="collapse" id="@collapseId">
                            <div class="card mb-2 collapse-card">
                                <div class="card-header">
                                    <div class="d-flex bd-highlight">
                                        <div class="p-2 w-100 bd-highlight text-light">
                                            <h5>@category</h5>
                                        </div>
                                        <div class="p-2 flex-shrink-1 bd-highlight">
                                            <!--Close Button-->
                                            <button class="close-button"
                                                    data-bs-toggle="collapse"
                                                    data-bs-target="#@collapseId"
                                                    aria-expanded="false"
                                                    aria-controls="collapseId">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-compact-up" viewBox="0 0 16 16">
                                                    <path fill-rule="evenodd" d="M7.776 5.553a.5.5 0 0 1 .448 0l6 3a.5.5 0 1 1-.448.894L8 6.56 2.224 9.447a.5.5 0 1 1-.448-.894l6-3z" />
                                                </svg>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <div class="row">
                                        <!--Sub Category List-->
                                        @foreach (var sub in Model.dishSubCategories[category])
                                        {
                                            var subId = "collapseSub" + category.Replace(" ", "") + sub.Replace(" ", "");
                                            <!--Sub Category Collapse Control Button-->
                                            <button class="btn sub-category-button text-light mb-2 " type="button"
                                                    data-bs-toggle="collapse"
                                                    data-bs-target="#@subId"
                                                    aria-expanded="false"
                                                    aria-controls="@subId">
                                                @sub
                                            </button>
                                            <!--Sub Category Collapse -->
                                            <div class="collapse" id="@subId">
                                                <div class="row">
                                                    @foreach (var dish in Model.dishes.Where(x => x.Category == category).Where(x => x.SubCategory == sub))
                                                    {
                                                        var dishOffcanvasId = "offcanvas" + dish.Id.ToString();
                                                        var dishOffcanvasDeleteId = "offcanvasDelete" + dish.Id.ToString();

                                                        <div class="col-3 mb-2">
                                                            <form class="d-grid" asp-page-handler="AddDishToOrder" asp-route-dishId="@dish.Id" asp-route-orderId="@orderId">
                                                                <button class="btn dish-btn text-light">@dish.Name @dish.Price</button>
                                                            </form>
                                                        </div>
                                                    }
                                                </div>
                                            </div>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
                <!--Left Column of Categories-->
                <div class="col-2">
                    <!--Category List-->
                    @foreach (var category in Model.dishCategories)
                    {
                        var collapseId = "collapse" + category.Replace(" ", "");
                        <!--Category Collapse Control Button-->
                        <div class="col-md-12 d-grid text-center mb-2 category-button">
                            <button class="btn text-light" type="button"
                                    data-bs-toggle="collapse"
                                    data-bs-target="#@collapseId"
                                    aria-expanded="false"
                                    aria-controls="@collapseId">
                                @category
                            </button>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>